dist: xenial
sudo: false
language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=1.2

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  # Use lock file for install so old version of phpstan is used.
  - travis_retry composer install -n --prefer-dist

script: ./vendor/bin/phpstan analyse
